### ISSUE TITLE
Numbering scheme

### ISSUE THREAD

**Issue by PatrickMassot** [avigad/mathematics_in_lean_source#1]
As I wrote in an email, I think 

> On Zulip, you can helpfully specify that you are asking about the third exercise by referring to it as "the third problem in exercises/logic/propositional_logic.lean."

is not robust enough. We need an immutable tag system. In my tutorials I explicitly number exercises, and reordering or deleting exercises is not meant to change tags.

**Comment by avigad** [comment]
How does this work? Do we manually make up names, like "exercise_with_sequences"? Do users see the name? Is it displayed with the exercise?

**Comment by PatrickMassot** [comment]
I the tutorials I write numbers on top of each exercise. But it's not convenient, there is nothing checking I don't duplicate numbers, and it will look weird when reordering will occur. I think we should use a random hexadecimal four digits identifier, generated by some helper script..

**Comment by avigad** [comment]
We seem to be doing fine without this, but we can revisit this if the need arises.
