### ISSUE TITLE
Git Pod set up failed

### ISSUE THREAD

**Issue by Seasawher** [avigad/mathematics_in_lean_source#114]
I can't open workspace of git pod. :(

![gitpod_failed](https://github.com/avigad/mathematics_in_lean_source/assets/47292598/07bab318-bcb6-414e-8acc-2cf2167b98a4)

**Comment by avigad** [comment]
This was addressed with #108 and seems to work now, but please let us know if you still have problems.

**Comment by Seasawher** [comment]
Thanks!
