### ISSUE TITLE
`by` could be used for easier solving

### ISSUE THREAD

**Issue by grekiki2** [avigad/mathematics_in_lean_source#125]
Is there any reason we skip `by` in this line? https://github.com/avigad/mathematics_in_lean_source/blob/02c54ebcf54bc5351ebadc00da198769bd607af8/MIL/C02_Basics/S02_Proving_Identities_in_Algebraic_Structures.lean#L382

Took me a bit of time to figure out why I was getting lean errors while trying to prove the statement.

**Comment by PatrickMassot** [comment]
No, this was a random variation. Thanks for pointing it out.
