### ISSUE TITLE
'iSup_delab' has already been declared

### ISSUE THREAD

**Issue by deepimpactmir** [avigad/mathematics_in_lean_source#136]
I am getting the following error when building `MIL.Common`

```
error: stdout:
./././MIL/Common.lean:81:4: error: 'iSup_delab' has already been declared
error: external command `/Users/username/.elan/toolchains/leanprover--lean4---v4.2.0-rc3/bin/lean` exited with code 1
```

It seems that `iSup_delab` has been actually added to `mathlib4` (5 days ago according to `git blame`).

**Comment by PatrickMassot** [comment]
Did you update the Mathlib version inside MIL? Users are not expected to do that. We will eventually update it, taking care of such issues.

**Comment by deepimpactmir** [comment]
Ah I see. Thanks for the help!
