### ISSUE TITLE
Term mode is now nicer

### ISSUE THREAD

**Issue by PatrickMassot** [avigad/mathematics_in_lean_source#16]
This is a global issue hence I'm not doing anything about it in the PR I'm currently preparing. A lot of things were written back in the old days when proof terms were completely opaque. With a recent Lean+VSCode, the tactic state get updated when you move the cursor through a proof term. So we need to explain that and rehabilitate term mode somehow. Unfortunately this needs going through the whole thing, and I didn't have that in mind yesterday while reading.

**Comment by avigad** [comment]
Now everything is different in Lean 4, but let's revisit when we think of what specifically we want to add.
