### ISSUE TITLE
Better installation instructions for VS Code

### ISSUE THREAD

**Issue by yuxi-liu-wired** [avigad/mathematics_in_lean_source#161]
I spent an hour getting confused by issues then I figured out why. Add these instructions to the installation process:

* After installing Lean 4 VS Code extension, Elan and GitHub.
* Clone the `mathematics_in_lean` repo.
* Open a terminal in the `mathematics_in_lean` folder, run `lake update`, then run `lake exe cache get`. This should take about 1 minute. Make sure the terminal shows that you are exactly in that folder, not a folder above or below it. It might fail if you use the internal terminal of VS Code, so don't use that.
* Open the folder in VS Code. It MUST be exactly this folder. It CANNOT be any other folder. If `mathematics_in_lean` is cloned to some other folder like `path\mathematics_in_lean`, then if you open `path` in VS Code, the lean server WILL FAIL.

I'm putting the error messages here so that other people can find this issue by Google search:

> Opened folder is not a valid Lean 4 project. Please open a valid Lean 4 project containing a 'lean-toolchain' file for full functionality.

> unknown package 'Mathlib'

**Comment by avigad** [comment]
You should not run `lake update`. What is wrong with the existing instructions? As far as I can tell, they are correct.
