### ISSUE TITLE
Antisymmetry of partial orders (section 2.5)

### ISSUE THREAD

**Issue by Taar2** [avigad/mathematics_in_lean_source#169]
I was doing the exercises in section **2.5 Proving Facts about Algebraic Structures** in VSCode and I spotted what I think are two issues. They are connected somewhat, see below, hence the single issue report.

What you call a "partial order" in section 2.5 (that is, some reflexive and transitive binary relation) is actually called a "preorder" in Wikipedia *and* the sources of mathlib (``Init/Order/Defs.lean``). According to those, a partial order is actually an antisymmetric preorder.

This causes not only some confusion for the readers who are already aware of this, but also causes some confusion down the road for those who are not, when you ask about proving lemmas about infimum and supremum in a lattice. Surely you can prove that if the infimum exists and is unique for all pairs of its arguments, then antisymmetry follows. But **antisymmetry is never mentioned in the text**, and neither the text nor the solutions mention that 

$$ \forall u\ \forall a\ \forall b\ \big((u\leq a \wedge u\leq b\wedge\forall x, x \leq a \wedge x \leq b \Rightarrow x \leq u) \Rightarrow u= a \sqcap b\big)$$

implies antisymmetry. Actually, none of the explicitly mentioned lemmas can be used to prove any equality (none has an equality at the rhs).

Sure, the astute reader could derive antisymmetry mentally and think about using ``le_antisymm`` in a lattice, but how could he/she possibly contemplate doing that if the text deliberately (?) avoids touching the subject of antisymmetry? Another possibility is that all this was a trick: in that case, why don't you comment about it in the solution?

I think the text would be better if antisymmetry was mentioned somewhere, or if you added the above fact as an exercise. And of course, I daresay all the mentions of "partial orders" should be replaced with "preorders".

(**great book**, btw)

**Comment by avigad** [comment]
Thanks for catching the mistake! You are right, leaving out antisymmetry was an oversight. I am traveling at the moment with a weak WiFi connection, but I'll make the correction soon.
