### ISSUE TITLE
Keep up with translations.json

### ISSUE THREAD

**Issue by PatrickMassot** [avigad/mathematics_in_lean_source#17]
The VSCode translations files actually has a [pretty active life](https://github.com/leanprover/vscode-lean/commits/master/translations.json) and I'm a bit worried that MIL contains many references to its current behavior. I'm not even sure it's currently up to date. It would be nice to have a way to flag those references and setup some CI, or at least have a command generating a list for manual inspection. The dream would be to have some rst command like:
```
..translation:: real, ℝ
```
that would register the fact we claimed `\real` is leading to `ℝ`, and those claims would be extracted as part of the build process.

**Comment by avigad** [comment]
I don't think this has been a problem, but we can revisit if necessary.
