### ISSUE TITLE
Potentially duplicate example

### ISSUE THREAD

**Issue by jkr26** [avigad/mathematics_in_lean_source#170]
Working through MIL as an intro to lean (which is great by the way, thank you!) Figured I would advise that seemingly the only difference between [these two examples](https://github.com/avigad/mathematics_in_lean_source/blob/master/MIL/C04_Sets_and_Functions/S01_Sets.lean#L86-L91) in section 4.1 is naming the theorem vs using an unnamed example. The way I read the associated text I thought more difference was intended here, so flagging. Please feel free to close as WAI if this is indeed the intention.

Thanks again for MIL!

**Comment by jkr26** [comment]
Also, read the next line, which indicates that just deleting `theorem foo` and replacing with `example` should fail...but as far as I can tell this still succeeds (perhaps there was a fix in Lean somewhere)? Or possibly this indicates that the named theorem is intended to be different?

**Comment by avigad** [comment]
@jkr26 Thanks for these corrections! These problems are all artifacts of a quick port from Lean 3 to Lean 4 last summer. I am traveling this week, but I will make the corrections when I am back in Pittsburgh.
