### ISSUE TITLE
.lake at .gitignore

### ISSUE THREAD

**Issue by sterraf** [avigad/mathematics_in_lean_source#171]
I'm planning to submit a PR for some typos, and after a `lake exe cache get` in my fork, the directory `.lake` was created. I adjusted my local `.gitignore` to dismiss this directory at the first line. Is this addition OK?

**Comment by alreadydone** [comment]
It's already ignored in mathlib two months ago after v4.3.0-rc2, so it seems reasonable to igmore it here too.

**Comment by PatrickMassot** [comment]
Yes. Lake has an important tradition of renaming that folder at least twice per year, so we need to adjust the gitignore every time. I forgot to do it when I bumped the Lean version before Christmas.
