### ISSUE TITLE
Does Lean expand `x^2` to `x^1 * x`? (Chapter 2.4)

### ISSUE THREAD

**Issue by sigongzi** [avigad/mathematics_in_lean_source#174]
I have read the chapter 2.4. It says

> In the last example, the exponent is a natural number, and applying dvd_mul_left forces Lean to expand the definition of `x^2` to `x * x^1`

```lean
example : x ∣ x ^ 2 := by
  show x ∣ x^1 * x
  apply dvd_mul_left
```

But I add show to code, it seems that lean expands it to `x^1 * x`. Which is wrong?

**Comment by avigad** [comment]
You are right! I will make the correction.
