### ISSUE TITLE
Lack of Introduction for Many Facts Used in the Tutorial

### ISSUE THREAD

**Issue by xiyuzhai** [avigad/mathematics_in_lean_source#183]
C02_Basics.S04 `dvd_gcd`, `gcd_dvd_right`, `gcd_dvd_left` are not introduced before they are needed. This is not the only place where things like this happen. There should be a full check to avoid things like this.

**Comment by xiyuzhai** [comment]
```

#check (Nat.gcd_zero_right n : Nat.gcd n 0 = n)
#check (Nat.gcd_zero_left n : Nat.gcd 0 n = n)
#check (Nat.lcm_zero_right n : Nat.lcm n 0 = 0)
#check (Nat.lcm_zero_left n : Nat.lcm 0 n = 0)

example : Nat.gcd m n = Nat.gcd n m := by
  sorry
end
```
The introduced facts
#check (Nat.gcd_zero_right n : Nat.gcd n 0 = n)
#check (Nat.gcd_zero_left n : Nat.gcd 0 n = n)
#check (Nat.lcm_zero_right n : Nat.lcm n 0 = 0)
#check (Nat.lcm_zero_left n : Nat.lcm 0 n = 0)
doesn't seem to be of any use.

**Comment by PatrickMassot** [comment]
This exercise is explicitly an exercise about guessing lemma names. It is introduced by the sentence
```quote
See if you can guess the names of the theorems you will need to prove the following:
```
and the lemmas that you quote are presented as justifying a claim from the previous paragraph, not as being related to an exercise.

So there is no issue at all here. Are you making the mistake of working on the exercises without reading the book? People sometimes do that and it is a very unproductive way to use this book.
