### ISSUE TITLE
When do we introduce simp?

### ISSUE THREAD

**Issue by PatrickMassot** [avigad/mathematics_in_lean_source#2]
From Zulip:
> Another general remark about my tutorials: I never tell my students about simp. That would be too powerful, and it would encourage them to try simp every other line instead of thinking.

Note that I do introduce `ring` and `linarith` very early. There are much better than `simp` because students are not too tempted to try them on each and every goal (although `linarith` is a bit too powerful here, especially when it comes to find contradiction, so I delay its introduction some more).

Anyway, we need to decide when we introduce simp.

**Comment by avigad** [comment]
It is now mentioned briefly in _Logic_, and we start to use it more substantially in _Sets, Functions, and Relations_. We don't give a detailed discussion or exhaustive overview, but, rather, show a few common usages. 

At some point, we should re-evaluate, decide whether to be more systematic, decide what more to say about `simp`, and decide where to say it.
