### ISSUE TITLE
namespace and open

### ISSUE THREAD

**Issue by PatrickMassot** [avigad/mathematics_in_lean_source#20]
I think we haven't really decided where we explain `namespace`, `open` and the dot notation (here I'm not even thinking of the magical one, simply using fully specified names). This kind of question is much easier in TPIL that takes a more systematic approach (or even more in the reference manual). So we need extra thinking here.

**Comment by avigad** [comment]
There is a very brief mention of namespaces at the end of this section: https://avigad.github.io/mathematics_in_lean/basics.html#more-on-order-and-divisibility.
Should we say more there?

**Comment by PatrickMassot** [comment]
Yes, that line implicitly assumes the meaning of `namespace` is clear, and only `open` needs to be explained. And of course we'll need to explain the dot notation magic somewhere, but not here. Note that even TPiL doesn't fully explain it since it explains it only in the context of structures.
