### ISSUE TITLE
Exercise for S2.5 requires setting implicit arguments

### ISSUE THREAD

**Issue by yannickseurin** [avigad/mathematics_in_lean_source#203]
I went through exercises of Chapter 2 and they can all be solved with the information in the chapter, except for this one from Section 2.5:

> example : x ⊔ y ⊔ z = x ⊔ (y ⊔ z)

This one requires setting implicit arguments explicitly such as `apply @le_sup_left _ _ y z` and this is not explained in Chapter 2. There's actually a hint at the beginning of Section 2.3 that this is something that maybe was planned but not done:

> The library designers have set the arguments `a`, `b` and `c` to `le_trans` implicit, so that Lean will not let you provide them explicitly (unless you really insist, as we will discuss later).

It would be nice to explain this so that all exercises are solvable from information introduced in the chapter.

**Comment by avigad** [comment]
Indeed, this was a stopgap fix when something broke at some point. We'll do a proper fix soon.

**Comment by avigad** [comment]
Note to ourselves: somewhere we also need to explain the new Lean 4 option of naming arguments, as in `apply le_sup_left (a := y) (b := z)`.

**Comment by ajirving** [comment]
There definitely needs to be a hint in the text to help with this.  Can someone explain why the corresponding example for inf doesn't require setting the arguments, you'd think they should be completely analogous.

**Comment by avigad** [comment]
The explanation is the one mentioned above: in Mathlib, for some reason the author of the `sup` version marked the arguments implicit. That should be fixed.

**Comment by PatrickMassot** [comment]
@avigad what do you think about the fix at 0d383c10525d8bb4f1840028860be4eb8f8b8ce7? Note this is in a branch, not in master.

**Comment by PatrickMassot** [comment]
After discussion with Jeremy, this fix has been merged.
