### ISSUE TITLE
bug in 8.1.4. Concrete groups?

### ISSUE THREAD

**Issue by KunihikoK3** [avigad/mathematics_in_lean_source#210]
`def myGroup := PresentedGroup {.of () ^ 3} deriving Group`

gives the error

`invalid dotted identifier notation, expected type is not of the form (... → C ...) where C is a constant
  ?m.50`

also see [live.lean](https://live.lean-lang.org/#code=import%20Mathlib%0D%0Adef%20myGroup%20%3A%3D%20PresentedGroup%20%7B.of%20()%20%5E%203%7D%20deriving%20Group)

`def myGroup := PresentedGroup {(FreeGroup.of () : FreeGroup Unit) ^ 3} deriving Group`

solves the problem for me

**Comment by PatrickMassot** [comment]
This is a bug in your setup, not in MIL. You probably try to use a version of Lean+Mathlib which is not compatible with MIL. If you follow the setup instructions then this issue won’t appear. The repository pins the Lean version [here](https://github.com/leanprover-community/mathematics_in_lean/blob/master/lean-toolchain) and Mathlib version [there](https://github.com/leanprover-community/mathematics_in_lean/blob/master/lake-manifest.json#L61). If you use Lean correctly then everything should work transparently. I just tried opening MIL on GitPod (so no personal configuration at all) and this group example works. If you insist on not using the tooling or if you copy paste code from MIL in a random project or live.lean-lang.org then you should expect nothing to work.
