### ISSUE TITLE
"rintros" used in text

### ISSUE THREAD

**Issue by SimonK00001** [avigad/mathematics_in_lean_source#212]
In `MIL/C03_Logic/S02_The_Existential_Quantifier.lean` the term "rintros" is used.
According to https://leanprover-community.github.io/mathlib_docs/tactics.html, "rintros" is an alias for "rintro". But in VSCode "rintros" creates the error "unknown tactic" if used in the file.
But this example in from the same file
```lean4
example : FnHasUb f → FnHasUb g → FnHasUb fun x ↦ f x + g x := by
  rintro ⟨a, ubfa⟩ ⟨b, ubgb⟩
  exact ⟨a + b, fnUb_add ubfa ubgb⟩
```
does work without problems. So I don't understand why "rintros" should not work.

**Comment by PatrickMassot** [comment]
Thanks for your message. The `rintros` in the book is a typo that I just fixed. The webpage mentioning the alias that you quote is a Lean 3 documentation webpage. Lean 3 is a completely obsolete version of Lean.
