### ISSUE TITLE
`dif_pos` versus `if_pos` in Chapter 4

### ISSUE THREAD

**Issue by yannickseurin** [avigad/mathematics_in_lean_source#214]
In Section 4.2, `dif_pos` and `dif_neg` are presented:

> The identity `dif_pos h` rewrites `if h : e then a else b` to `a` given `h : e`, and, similarly, `dif_neg h` rewrites it to `b` given `h : ¬ e`.

But later in Section 4.3, one needs to use `if_pos`  and `if_neg` instead. The difference is not explained and I was not able to understand exactly what's going on even from the mathlib documentation.

**Comment by PatrickMassot** [comment]
Thanks, I added a sentence of explanation.
