### ISSUE TITLE
`cases` versus `cases'`

### ISSUE THREAD

**Issue by yannickseurin** [avigad/mathematics_in_lean_source#216]
Towards the end of Section 4.3 one reads

> The tactic `cases n with n` splits on the cases `g y ∈ sbAux f g 0` and `g y ∈ sbAux f g n.succ`.

But actually the line in the code is `rcases n with _ | n`.
In fact `cases n with n` does not work, one can use alternatively `cases' n with n`.

Same in Section 5.1 where one reads

> The line `cases r with r` replaces the goal with two versions: one in which `r` is replaced by `0`, and the other in which `r` is replaces by `r.succ`, the successor of `r`.

but the actual line is `rcases r with _ | r`.

Also, in the Lean Infoview window, `r+1` is displayed rather than `r.succ`.

**Comment by PatrickMassot** [comment]
Thanks a lot. I fixed those issues. Keeping the code snippets that appear inline in the text up to date is very challenging since they are not checked by Lean. Those were remnants of older versions of Lean.
