### ISSUE TITLE
obtain

### ISSUE THREAD

**Issue by PatrickMassot** [avigad/mathematics_in_lean_source#25]
Do we want to mention obtain in chapter 3 where we discuss `rintros` and `rcases`?

**Comment by avigad** [comment]
I just took a look at this, and I think the answer is "no". The most natural use of `obtain` can be handled just as easily with `rcases`, and it's hard to come up with an non-contrived instance of the more complicated usage.

In Chapter 3, we bombard the reader with new ideas and tactics. I think we should try to avoid information overload and focus on the most common idioms. If, in a later chapter, we find a compelling reason to use `obtain`, let's explain it there.

**Comment by PatrickMassot** [comment]
Ok, good. I'm closing then (if Rob or Kevin disagree we can still reopen but let's try to clean up things this week).
