### ISSUE TITLE
Basic definitions in Sets

### ISSUE THREAD

**Issue by PatrickMassot** [avigad/mathematics_in_lean_source#32]
For some reason I forgot a bunch of margin notes from my printed copy of the book when I commented to Chapter 4 PR. 

* Maybe warn that empty and univ often need a type ascription
* Mention the notation in and notin from the beginning, use it to actually spell out the definition of subset and intersection instead of alluding to them
* After commutativity of intersection, there is a mysterious explanation of `$` without any `$` in sight.

**Comment by avigad** [comment]
Regarding the $: it is on the previous line, no?

(I will address the other two.)

**Comment by PatrickMassot** [comment]
Ok, I was blind not seeing the dollar sign.
