### ISSUE TITLE
Git clone via HTTPS instead of SSH

### ISSUE THREAD

**Issue by Vierkantor** [avigad/mathematics_in_lean_source#71]
We tried following the installation instructions on a new computer (macOS 12 Monterey) and got an error on the second install step:

> In a terminal, navigate to the folder where you want to put a copy of the repository, and type `git clone git@github.com:leanprover-community/mathematics_in_lean.git` to fetch it from github.

The error was: `permission denied (publickey)`. It looks like this computer has no public keys at all in the `~/.ssh` folder. (Don't you also need to connect your key to a GitHub account?)

Should the instructions instead suggest the HTTPS clone url `https://github.com/leanprover-community/mathematics_in_lean.git`, since it does not require any setup?

**Comment by avigad** [comment]
2012068.
