### ISSUE TITLE
unicode in pdf doesn't show

### ISSUE THREAD

**Issue by fpvandoorn** [avigad/mathematics_in_lean_source#74]
The pdf https://leanprover-community.github.io/mathematics_in_lean/mathematics_in_lean.pdf doesn't show all unicode characters, like the blackboard 1 in chapter 7.

**Comment by PatrickMassot** [comment]
Thanks for pointing this out. Could you please check you no longer see this issue?

**Comment by fpvandoorn** [comment]
Yes, it is fixed now!
