### ISSUE TITLE
`Prime` norm num extension

### ISSUE THREAD

**Issue by kmill** [avigad/mathematics_in_lean_source#83]
The extension now lives in the `Mathlib.Tactic.NormNum.Prime` module, and you don't get it automatically by importing the definitions like you did in Lean 3 (we're trying to keep theory and meta code separate in mathlib4).

This tripped up a number of students during the first week of the MSRI workshop, and there was another question about it [on Zulip](https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/7.20is.20prime.3F/near/371587048) which reminded me to make an issue.

**Comment by PatrickMassot** [comment]
I fixed that issue in b3adcb02f31dc31b6f1612df0cbb30f11e417297.
