### ISSUE TITLE
Automation chapter (RFC)

### ISSUE THREAD

**Issue by avigad** [avigad/mathematics_in_lean_source#85]
Initially, we made the decision to introduce automation piecemeal. Tactics like `ring`, `abel`, and `linarith` are introduced in Chapter 2. There are a few references to `simp` in Chapter 3, but it is only discussed in any detail in Chapter 4. And there is a lot of useful automation that we do not yet discuss at all:

- congr
- linear_combination
- polyrith
- positivity
- gcongr
- tauto
- aesop

The list is likely to grow quickly in Lean 4. Since the point of Chapters 2, 3, and 4 are to introduce `rw`, `apply`, and logical manipulations, it makes sense to favor manual calculation there. But beyond that point, we'd do well to show students/readers how to use automation like this wherever it is appropriate.

I suggest we add a new chapter, `Automation`, in between the current Chapters 4 and 5, and then systematically use automation after that wherever it is appropriate. We can discuss all the items listed above, and show how they can be used to simplify a lot of the examples and exercises from the previous chapters. I suggest using `simp` in restricted ways in Chapters 3 and 4, but deferring a full discussion to the new chapter.

I am curious to hear whether others think this is a good idea, and, if so, what else should be included in this chapter.

**Comment by PatrickMassot** [comment]
I'm not sure we need to aim for a Automation chapter. A lot of the tactics you mention are really about computation, and tauto can easily be discussed at the end of the logic chapter. So we could have a Computations chapter, and find some place for aesop somewhere.

**Comment by avigad** [comment]
When I hear "computation" I think of computer programming. I think you mean something more like "calculation"? So we leave discussions of `simp` and `tauto` and `aesop` for other places, and make the chapter about doing algebraic calculations, proving inequalities, etc.? That sounds good to me.

**Comment by PatrickMassot** [comment]
Yes, I meant calculation.

**Comment by avigad** [comment]
These plans are now on the Wiki page.
