### ISSUE TITLE
in lean4 07-15 nightly the package proof widget should use version >= v0.0.12

### ISSUE THREAD

**Issue by alissa-tung** [avigad/mathematics_in_lean_source#97]

**Comment by avigad** [comment]
All the packages downstream of Mathlib are synchronized to the corresponding version of Mathlib, so I don't think this is something we want to mess with.

**Comment by alissa-tung** [comment]
> All the packages downstream of Mathlib are synchronized to the corresponding version of Mathlib, so I don't think this is something we want to mess with.

Thank you!
